# Generated by Django 6.0.2 on 2026-02-12 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('occurred_date', models.DateField()),
                ('type', models.TextField(choices=[('expense', '지출'), ('income', '수입')])),
                ('amount', models.IntegerField()),
                ('currency', models.TextField(default='KRW')),
                ('category', models.TextField()),
                ('subcategory', models.TextField(default='기타')),
                ('merchant', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-occurred_date', '-created_at'],
                'indexes': [models.Index(fields=['user_id', '-occurred_date'], name='idx_tx_user_date'), models.Index(fields=['user_id', 'category'], name='idx_tx_user_cat'), models.Index(fields=['user_id', 'subcategory'], name='idx_tx_user_subcat')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('idem_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tx', models.ForeignKey(db_column='tx_id', on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction')),
            ],
            options={
                'db_table': 'idempotency_keys',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'idem_key'), name='pk_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('action', models.TextField(choices=[('create', '생성'), ('update', '수정'), ('delete', '삭제'), ('undo', '취소')])),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tx', models.ForeignKey(blank=True, db_column='tx_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.transaction')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='idx_audit_user_created')],
            },
        ),
    ]
